### ISSUE TITLE
Bug: AttributeError: 'opennmt_opts' object has no attribute 'int8'

### ISSUE THREAD

**Issue by Kentoseth** [mikahama/haracat#1]
Hello, I followed the instructions to install haracat as the repo says.

Here is the code and output of the bug.

```python

from haracat import diacritics_sentence, diacritics_sentences

print(diacritics_sentence("قبل أيام كثيرة. كثيرة جدا.".split(" ")))
```

Output log:

> print(diacritics_sentence("قبل أيام كثيرة. كثيرة جدا.".split(" ")))
>   File ".../lib/python3.8/site-packages/haracat/normalizer.py", line 47, in diacritics_sentence
>     res = _normalize_chunks(chunks)
>   File ".../lib/python3.8/site-packages/haracat/normalizer.py", line 54, in _normalize_chunks
>     res = call_onmt(chunks, model_name, n_best=1)
>   File ".../lib/python3.8/site-packages/natas/normalize.py", line 141, in call_onmt
>     fields, model, model_opt = _give_model(model_name)
>   File ".../lib/python3.8/site-packages/natas/normalize.py", line 131, in _give_model
>     _load_model(name)
>   File ".../lib/python3.8/site-packages/natas/normalize.py", line 126, in _load_model
>     m = load_test_model(opt)
>   File ".../lib/python3.8/site-packages/onmt/decoders/ensemble.py", line 130, in load_test_model
>     onmt.model_builder.load_test_model(opt, model_path=model_path)
>   File ".../lib/python3.8/site-packages/onmt/model_builder.py", line 96, in load_test_model
>     elif opt.int8:
> AttributeError: 'opennmt_opts' object has no attribute 'int8'

Thanks!

**Comment by mikahama** [comment]
It seems you don't have a correct version of opennmt-py. This library uses my other library called natas that has a requirement OpenNMT-py==1.0.0. Ensure that you have the right version installed and let me know if it still doesn't work

**Comment by Kentoseth** [comment]
I am still getting an issue after forcing the downgrade of `OpenNMT-py` to 1.0.0

The error is:

> .../lib/python3.8/site-packages/onmt/translate/beam_search.py:187: UserWarning: An output with one or more elements was resized since it had shape [5], which does not match the required output shape [1, 5].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /pytorch/aten/src/ATen/native/Resize.cpp:19.)
>   torch.mul(self.topk_scores, length_penalty, out=self.topk_log_probs)
> Traceback (most recent call last):
>   File "test.py", line 4, in <module>
>     print(diacritics_sentence("قبل أيام كثيرة. كثيرة جدا.".split(" ")))
>   File ".../lib/python3.8/site-packages/haracat/normalizer.py", line 47, in diacritics_sentence
>     res = _normalize_chunks(chunks)
>   File ".../lib/python3.8/site-packages/haracat/normalizer.py", line 54, in _normalize_chunks
>     res = call_onmt(chunks, model_name, n_best=1)
>   File ".../lib/python3.8/site-packages/natas/normalize.py", line 151, in call_onmt
>     t.translate(
>   File ".../lib/python3.8/site-packages/onmt/translate/translator.py", line 351, in translate
>     batch_data = self.translate_batch(
>   File ".../lib/python3.8/site-packages/onmt/translate/translator.py", line 546, in translate_batch
>     return self._translate_batch_with_strategy(batch, src_vocabs,
>   File ".../lib/python3.8/site-packages/onmt/translate/translator.py", line 677, in _translate_batch_with_strategy
>     decode_strategy.advance(log_probs, attn)
>   File ".../lib/python3.8/site-packages/onmt/translate/beam_search.py", line 190, in advance
>     torch.div(self.topk_ids, vocab_size, out=self._batch_index)
> RuntimeError: result type Float can't be cast to the desired output type Long

**Comment by mikahama** [comment]
The required version is torch==1.2
Please note that pip will complain about version mismatch during the installation, if you have a wrong version of torch or opennmt-py in your system.

**Comment by Kentoseth** [comment]
torch==1.2 does not exist on PyPi any longer. I cleared my pip cache and tried to install natas first. Here is the output:

> Collecting natas
>   Downloading natas-1.0.6-py2.py3-none-any.whl (2.2 MB)
>      |████████████████████████████████| 2.2 MB 210 kB/s 
> ERROR: Could not find a version that satisfies the requirement torch==1.2 (from natas) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1)
> ERROR: No matching distribution found for torch==1.2 (from natas)

Trying to force the lookup of that specific version:

`pip install 'torch==1.2'`

Same output:

> ERROR: Could not find a version that satisfies the requirement torch==1.2 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1)
> ERROR: No matching distribution found for torch==1.2

**Comment by mikahama** [comment]
You can try out with the other torch versions (some of them might be compatible with opennmt-py) or use Python 3.7
